changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Novità
      labels:
        - enhancement
    - title: Correzioni
      labels:
        - bug
    - title: Documentazione
      labels:
        - documentation
    - title: Altro
      labels:
        - "*"
